# Generated by Django 5.2.15 on 2026-06-25 16:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('default_terms_and_conditions', models.TextField(default='1. Payment should be made within the agreed timeline.\n2. Any delay in payment may attract additional charges.\n3. Taxes are applicable as per government regulations.')),
                ('default_declaration', models.TextField(default='We hereby declare that the details mentioned in this invoice are true and correct to the best of our knowledge.')),
                ('default_payment_terms', models.CharField(default='Payment should be made within the agreed timeline.', max_length=160)),
                ('invoice_number_format', models.CharField(default='{company3}{client3}-{date_ddmmyyyy}-{sequence:03d}', max_length=140)),
                ('date_separator', models.CharField(blank=True, default='', max_length=3)),
                ('prefix_separator', models.CharField(blank=True, default='-', max_length=3)),
                ('running_sequence_length', models.PositiveSmallIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application setting',
                'verbose_name_plural': 'Application settings',
            },
        ),
    ]
