# Generated by Django 5.2.15 on 2026-06-26 05:14

import billing.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_applicationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Name / Company Name')),
                ('vendor_type', models.CharField(choices=[('Individual Developer', 'Individual Developer'), ('Freelancer', 'Freelancer'), ('Company', 'Company'), ('Agency', 'Agency'), ('Consultant', 'Consultant'), ('Other', 'Other')], max_length=40)),
                ('contact_person', models.CharField(blank=True, max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('pin_code', models.CharField(blank=True, max_length=12)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('bank_details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='authorized_signature',
            field=models.FileField(blank=True, upload_to='company_signatures/', validators=[billing.validators.validate_signature_file]),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('project_name', models.CharField(max_length=180)),
                ('project_requirement', models.TextField()),
                ('project_type', models.CharField(choices=[('IT Consulting', 'IT Consulting'), ('Website Development', 'Website Development'), ('Mobile App Development', 'Mobile App Development'), ('Web Application', 'Web Application'), ('Digital Marketing', 'Digital Marketing'), ('SEO', 'SEO'), ('Branding', 'Branding'), ('Software Development', 'Software Development'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=40)),
                ('custom_project_type', models.CharField(blank=True, max_length=120)),
                ('project_description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Quotation Sent', 'Quotation Sent'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Enquiry', max_length=30)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('estimated_quote', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approved_quote', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('client_advance_amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('client_advance_received_date', models.DateField(blank=True, null=True)),
                ('client_next_advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('client_next_advance_expected_date', models.DateField(blank=True, null=True)),
                ('client_total_amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('client_pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('client_payment_remarks', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='billing.client')),
            ],
            options={
                'ordering': ['-created_at', 'project_name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.project'),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(max_length=140)),
                ('work_description', models.TextField(blank=True)),
                ('developer_cost_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('developer_final_project_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_amount_sent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_sent_date', models.DateField(blank=True, null=True)),
                ('next_advance_amount_to_send', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('next_advance_expected_date', models.DateField(blank=True, null=True)),
                ('total_amount_paid_to_developer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pending_amount_to_developer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('assignment_status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Assigned', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='billing.developervendor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='billing.project')),
            ],
            options={
                'ordering': ['project', 'developer_vendor'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Other', 'Other')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Milestone Payment', 'Milestone Payment'), ('Final Payment', 'Final Payment'), ('Other', 'Other')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_payments', to='billing.projectassignment')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Other', 'Other')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Milestone Payment', 'Milestone Payment'), ('Final Payment', 'Final Payment'), ('Other', 'Other')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to='billing.project')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
