# Generated by Django 5.2.15 on 2026-06-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_invoice_gst_flags(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    Invoice.objects.filter(gst_amount__gt=0).update(apply_gst=True)
    Invoice.objects.filter(gst_amount=0).update(apply_gst=False)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_developervendor_company_authorized_signature_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='apply_gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Cancelled', 'Cancelled'), ('Deleted', 'Deleted')], default='Final', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Recurring', 'Recurring')], default='One Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Enquiry', 'Enquiry'), ('Quotation Sent', 'Quotation Sent'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Enquiry', max_length=30),
        ),
        migrations.RunPython(set_existing_invoice_gst_flags, migrations.RunPython.noop),
    ]
