# Generated by Django 5.2.15 on 2026-06-26 13:34

from django.db import migrations, models


def mark_soft_deleted_clients(apps, schema_editor):
    Client = apps.get_model("billing", "Client")
    Client.objects.filter(is_deleted=True).update(client_status="Deleted")


def restore_deleted_status_to_active(apps, schema_editor):
    Client = apps.get_model("billing", "Client")
    Client.objects.filter(client_status="Deleted").update(client_status="Active")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_client_deleted_at_client_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=20),
        ),
        migrations.RunPython(mark_soft_deleted_clients, restore_deleted_status_to_active),
    ]
