# Generated by Django 5.2.15 on 2026-06-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_client_requires_gst_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HsnSacCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'HSN/SAC code',
                'verbose_name_plural': 'HSN/SAC codes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_sac_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.hsnsaccode'),
        ),
    ]
