# Generated by Django 5.2.15 on 2026-06-27 04:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_hsnsaccode_company_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='advance_amount_sent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='developer_cost_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='developer_final_project_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='next_advance_amount_to_send',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='pending_amount_to_developer',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='total_amount_paid_to_developer',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
