# Generated by Django 5.2.15 on 2026-06-27 13:59

from decimal import Decimal
from django.db import migrations, models


def populate_existing_project_gst_fields(apps, schema_editor):
    Project = apps.get_model("billing", "Project")
    for project in Project.objects.all().only(
        "pk",
        "approved_quote",
        "client_total_amount_received",
    ):
        approved_quote = project.approved_quote or Decimal("0.00")
        client_received = project.client_total_amount_received or Decimal("0.00")
        client_pending = approved_quote - client_received
        if client_pending < Decimal("0.00"):
            client_pending = Decimal("0.00")
        Project.objects.filter(pk=project.pk).update(
            project_base_amount=approved_quote,
            project_gst_amount=Decimal("0.00"),
            project_total_with_gst=approved_quote,
            client_pending_amount=client_pending,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_applicationsetting_backup_reminder_dismissed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_amount_gst_type',
            field=models.CharField(choices=[('WITHOUT_GST', 'Without GST / GST Not Applicable'), ('GST_EXTRA', 'GST Extra / Amount Before GST'), ('GST_INCLUDED', 'GST Included in Approved Amount'), ('PARTIAL_GST', 'Partial GST')], default='WITHOUT_GST', max_length=30, verbose_name='Approved Client Amount GST Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='partial_gst_taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='project_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='project_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='project_gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='project_total_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunPython(populate_existing_project_gst_fields, migrations.RunPython.noop),
    ]
