# Generated by Django 5.2.15 on 2026-08-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoice_currency_project_currency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('project', 'developer_vendor'), name='unique_project_developer_assignment'),
        ),
    ]
